[pytest]
pythonpath = .
testpaths = tests

markers =
    smoke: critical basic tests
    regression: regression test suite
    nightly: long-running nightly tests
    stress: stress and performance tests

addopts =
    -vv
    --log-cli-level=INFO
    --capture=tee-sys
    --junitxml=report.xml
    --html=pytest_report.html
    --self-contained-html
    --cov=library
    --cov=repositories
    --cov-report=term-missing
    --cov-report=xml
    --cov-report=html
